# For more information on the use of this file, please check:
# https://docs.streamlit.io/library/advanced-features/configuration

[browser]
# Opt out of sending user statistics (telemetry) to Streamlit.
gatherUsageStats = false


[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 1024

